baseURL = "" # This is populated by the github deploy workflow and is equal to "<domainName>"
languageCode = "en-us"
title = "Apache Iceberg"

[params]
  description = "The open table format for analytic datasets."
  latestVersions.iceberg = "0.13.1"
  docsBaseURL = ""

[[params.social]]
  title = "Community"
  icon = "comments"
  rel_url = "community"
[[params.social]]
  title = "github"
  icon = "github"
  url = "https://github.com/apache/iceberg"
[[params.social]]
  title = "slack"
  icon = "slack"
  url = "https://join.slack.com/t/apache-iceberg/shared_invite/zt-tlv0zjz6-jGJEkHfb1~heMCJA3Uycrg"  
